In [1]:
from sklearn.datasets import load_iris
iris=load_iris();

In [7]:
import pandas as pd
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df["Flower"]=iris.target
df["Flower"]=df["Flower"].apply(lambda x:iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,train_size=0.7)

In [35]:
from sklearn.svm import SVC
model=SVC(kernel="rbf",C=10,gamma="auto")
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9555555555555556

In [37]:
from sklearn.model_selection import cross_val_score 

In [38]:
cross_val_score(SVC(kernel="linear", C=10, gamma="auto"), iris.data,iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [39]:
cross_val_score(SVC(kernel="rbf", C=10, gamma="auto"), iris.data,iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [41]:
cross_val_score(SVC(kernel="rbf", C=20, gamma="auto"), iris.data,iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [47]:
import numpy as np
k=["linear","rbf"]
c=[1,10,20]
avg={}
for ke in k:
    for cv in c:
        x=cross_val_score(SVC(kernel=ke, C=cv, gamma="auto"), iris.data,iris.target, cv=5)
        avg[ke+"_"+str(cv)]=np.average(x)
avg

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}

In [62]:
# above for loop can be implemented with inbuilt method in SKLEARN
# is does all combinations of the values using K-fold validation
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(SVC(gamma="auto"), {
    'C':[1,10,20],
    'kernel':["linear", 'rbf']
}, cv=6, return_train_score=False)
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00212967, 0.00156955, 0.00065025, 0.00082839, 0.00083637,
        0.00083021]),
 'std_fit_time': array([0.00054259, 0.00078616, 0.00046117, 0.00037059, 0.00037405,
        0.00037145]),
 'mean_score_time': array([0.00142193, 0.00068601, 0.00049921, 0.00049686, 0.00049659,
        0.00016757]),
 'std_score_time': array([0.00050497, 0.00048716, 0.00049922, 0.00049706, 0.00049659,
        0.00037469]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'}],


In [63]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.002130      0.000543         0.001422        0.000505       1   
1       0.001570      0.000786         0.000686        0.000487       1   
2       0.000650      0.000461         0.000499        0.000499      10   
3       0.000828      0.000371         0.000497        0.000497      10   
4       0.000836      0.000374         0.000497        0.000497      20   
5       0.000830      0.000371         0.000168        0.000375      20   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}               0.96   
1          rbf      {'C': 1, 'kernel': 'rbf'}               0.96   
2       linear  {'C': 10, 'kernel': 'linear'}               1.00   
3          rbf     {'C': 10, 'kernel': 'rbf'}               0.96   
4       linear  {'C': 20, 'kernel': 'linear'}               1.00   
5          rbf     {'C': 20, 'kernel': 'rbf'}               0.96   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0               0.96               0.96               1.00   
1                1.0               0.96               0.92               0.96   
2                1.0               0.92               0.92               0.96   
3                1.0               0.92               0.92               0.96   
4                1.0               0.92               0.92               0.96   
5                1.0               0.88               0.92               0.96   

   split5_test_score  mean_test_score  std_test_score  rank_test_score  
0                1.0         0.980000        0.020000                1  
1                1.0         0.966667        0.027487                2  
2                1.0         0.966667        0.035901                2  
3                1.0         0.960000        0.032660                5  
4                1.0         0.966667        0.035901                2  
5                1.0         0.953333        0.042687                6

In [64]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1       1          rbf         0.966667
2      10       linear         0.966667
3      10          rbf         0.960000
4      20       linear         0.966667
5      20          rbf         0.953333

In [65]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_fe

In [66]:
clf.best_score_

0.98

In [67]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [74]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(SVC(gamma="auto"), {
    'C':[1,10,20],
    'kernel':["linear", 'rbf']
}, cv=6, return_train_score=False, n_iter=2)
rs.fit(iris.data,iris.target)
df1=pd.DataFrame(rs.cv_results_)
df1[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear             0.98
1      10          rbf             0.96

In [75]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [87]:
model= {
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,10,20], 'kernel':['linear','rbf']
        }
    },
    'random_for':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_reg':{
        'model':LogisticRegression(solver="liblinear",multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    }
}
model

{'svm': {'model': SVC(gamma='auto'),
  'params': {'C': [1, 10, 20], 'kernel': ['linear', 'rbf']}},
 'random_for': {'model': RandomForestClassifier(),
  'params': {'n_estimators': [1, 5, 10]}},
 'logistic_reg': {'model': LogisticRegression(solver='liblinear'),
  'params': {'C': [1, 5, 10]}}}

In [79]:
scores=[]
for mo,mp in model.items():
    cls=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    cls.fit(iris.data,iris.target)
    scores.append({
        'model':mo,
        'best_score':cls.best_score_,
        'Best_parameters':cls.best_params_
    })

In [82]:
a=pd.DataFrame(scores)
a

model  best_score               Best_parameters
0           svm    0.980000  {'C': 1, 'kernel': 'linear'}
1    random_for    0.953333           {'n_estimators': 5}
2  logistic_reg    0.966667                      {'C': 5}