In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [3]:
digits=load_digits()

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,train_size=0.7)

In [5]:
model=LogisticRegression(max_iter=5000)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9685185185185186

In [6]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.987037037037037

In [7]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [8]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
def get_score(model, x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [11]:
get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test)

0.9703703703703703

In [12]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [13]:
score_l=[]
score_svc=[]
score_rf=[]
for train_index, test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    score_l.append(get_score(LogisticRegression(max_iter=4000), x_train,x_test,y_train,y_test))
    score_svc.append(get_score(SVC(), x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(), x_train,x_test,y_train,y_test))

In [14]:
score_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [15]:
score_rf

[0.9415692821368948, 0.9549248747913188, 0.9265442404006677]

In [16]:
score_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [17]:
from sklearn.model_selection import cross_val_score

In [19]:
cross_val_score(LogisticRegression(max_iter=3000),digits.data,digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [20]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.92777778, 0.90833333, 0.96100279, 0.95821727, 0.91643454])